/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MetodosNumericos;
    import java.math.*;

import java.text.DecimalFormat;

/**
 *
 * @author Admin
 */
public class Tema1 extends javax.swing.JFrame {

    /**
     * Creates new form Tema1
     */
    public Tema1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ValorReal = new javax.swing.JLabel();
        campoR = new javax.swing.JTextField();
        VALORPROMEDIO = new javax.swing.JLabel();
        campoA = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RESULTADOabsoluto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RESULTADOrelativo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantiTRUNCAR = new javax.swing.JTextField();
        REONDEAR = new javax.swing.JRadioButton();
        TRUNCAR = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        RESET = new javax.swing.JToggleButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        Menu.setText("Menú");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Salir.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("CALCULAR ERRORES");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        ValorReal.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        ValorReal.setText("VALOR REAL");
        getContentPane().add(ValorReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        campoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRActionPerformed(evt);
            }
        });
        getContentPane().add(campoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 180, 30));

        VALORPROMEDIO.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        VALORPROMEDIO.setText("VALOR PROMEDIO");
        getContentPane().add(VALORPROMEDIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        campoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAActionPerformed(evt);
            }
        });
        getContentPane().add(campoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 180, 30));

        calcular.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        calcular.setText("CALCULAR");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("RESULTADOS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("ERROR ABSOLUTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        RESULTADOabsoluto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESULTADOabsolutoActionPerformed(evt);
            }
        });
        getContentPane().add(RESULTADOabsoluto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 170, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("ERROR RELATIVO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        RESULTADOrelativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESULTADOrelativoActionPerformed(evt);
            }
        });
        getContentPane().add(RESULTADOrelativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 170, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("¿DESEAS REDONDEAR O TRUNCAR?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("¿Cuántos números?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        cantiTRUNCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantiTRUNCARActionPerformed(evt);
            }
        });
        getContentPane().add(cantiTRUNCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 40, 30));

        REONDEAR.setBackground(new java.awt.Color(0, 0, 0));
        REONDEAR.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        REONDEAR.setForeground(new java.awt.Color(240, 240, 240));
        REONDEAR.setText("REDONDEAR");
        REONDEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REONDEARActionPerformed(evt);
            }
        });
        getContentPane().add(REONDEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        TRUNCAR.setBackground(new java.awt.Color(0, 0, 0));
        TRUNCAR.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        TRUNCAR.setForeground(new java.awt.Color(240, 240, 240));
        TRUNCAR.setText("TRUNCAR");
        TRUNCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRUNCARActionPerformed(evt);
            }
        });
        getContentPane().add(TRUNCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("RESULTADOS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("ERROR ABSOLUTO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 170, 40));

        jLabel5.setFont(new java.awt.Font("Sitka Small", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("ERROR RELATIVO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 160, 40));

        RESET.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });
        getContentPane().add(RESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, -1, -1));

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo/IMG-20190202-WA0031.jpg"))); // NOI18N
        Fondo.setText("nm");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 695));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        MenuTemas tema = new MenuTemas();
        tema.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void campoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRActionPerformed
        
    }//GEN-LAST:event_campoRActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        
        
         String valorR, valorA;
        float flotanteR, flotanteA;
        
        valorR=campoR.getText();
        valorA=campoA.getText();
        flotanteA=Float.parseFloat(valorA);
        flotanteR=Float.parseFloat(valorR);
        
        float valorAbsoluto, valorRelativo;
        
        valorAbsoluto=flotanteR-flotanteA;
        if(valorAbsoluto < 0){
            valorAbsoluto*=-1;
        }
         valorRelativo=(flotanteR-flotanteA)/flotanteR;
        if(valorRelativo < 0){
            valorRelativo*=-1;
        }
        
       
        String absoluto, relativo;
        absoluto=Float.toString(valorAbsoluto);
        relativo=Float.toString(valorRelativo);
        RESULTADOabsoluto.setText(absoluto);
        RESULTADOrelativo.setText(relativo);                                   
    }//GEN-LAST:event_calcularActionPerformed

    private void campoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAActionPerformed
        
    }//GEN-LAST:event_campoAActionPerformed

    private void RESULTADOabsolutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESULTADOabsolutoActionPerformed
        
    }//GEN-LAST:event_RESULTADOabsolutoActionPerformed

    private void REONDEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REONDEARActionPerformed
    Double reAb = Double.parseDouble(RESULTADOabsoluto.getText());
    Double reRe = Double.parseDouble(RESULTADOrelativo.getText());
    int cant = Integer.parseInt(cantiTRUNCAR.getText());
     
    /*double parteEnte,parteEntera,reAb1,reRe1;
     reAb1=reAb;
     parteEnte=Math.floor(reAb);
     reAb1=(reAb1-parteEnte)*Math.pow(10,cant);
    reAb1 =Math.round(reAb1);
    reAb1 =(reAb1/Math.pow(10,cant))+parteEnte;
     
    reRe1=reRe;
   parteEntera=Math.floor(reRe);
    reRe1=(reRe1-parteEntera)*Math.pow(10,cant);
    reRe1 =Math.round(reRe1);
    reRe1 =(reRe1/Math.pow(10,cant))+parteEntera;*/
    
    cant*=100;
    Double reAb1 = Math.rint(reAb*cant)/cant;
    Double reRe1 = Math.rint(reRe*cant)/cant;
    
    String reAb2 = String.valueOf(reAb1);
    String reRe2 = String.valueOf(reRe1);
    jTextField1.setText(reAb2);
    jTextField2.setText(reRe2);
    }//GEN-LAST:event_REONDEARActionPerformed

    private void TRUNCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRUNCARActionPerformed
        String cantidad = cantiTRUNCAR.getText();
        int canti= Integer.parseInt(cantidad);
        String Ra = RESULTADOabsoluto.getText();
        double doble1 = Double.parseDouble(Ra);
        doble1 = Math.round( doble1 * Math.pow(10, canti)) / Math.pow(10, canti); 
        String doble2 = String.valueOf(doble1);
        jTextField1.setText(doble2);
        String Rr = RESULTADOrelativo.getText();
        double doble3 = Double.parseDouble(Rr);
        doble3 = Math.round( doble3 * Math.pow(10, canti)) / Math.pow(10, canti); 
        String doble4 = String.valueOf(doble3);
        jTextField2.setText(doble4);
                
   
        
        
    }//GEN-LAST:event_TRUNCARActionPerformed

    private void cantiTRUNCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantiTRUNCARActionPerformed
        
    }//GEN-LAST:event_cantiTRUNCARActionPerformed

    private void RESULTADOrelativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESULTADOrelativoActionPerformed
        
    }//GEN-LAST:event_RESULTADOrelativoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        RESULTADOabsoluto.setText("");
        RESULTADOrelativo.setText("");
        campoA.setText("");
        campoR.setText("");
        cantiTRUNCAR.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        REONDEAR.setSelected(false);
        TRUNCAR.setSelected(false);
    }//GEN-LAST:event_RESETActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tema1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tema1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Menu;
    private javax.swing.JRadioButton REONDEAR;
    private javax.swing.JToggleButton RESET;
    private javax.swing.JTextField RESULTADOabsoluto;
    private javax.swing.JTextField RESULTADOrelativo;
    private javax.swing.JButton Salir;
    private javax.swing.JRadioButton TRUNCAR;
    private javax.swing.JLabel VALORPROMEDIO;
    private javax.swing.JLabel ValorReal;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField campoA;
    private javax.swing.JTextField campoR;
    private javax.swing.JTextField cantiTRUNCAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
